name: Upload website to S3

on:
  push:
    branches: [ master ]

#test adding custom policy to role
#changed policy to reflect just user/repo
#updated policy to include sts
env:
  
  AWS_REGION : "us-east-1" #Change to reflect your Region
  BUCKET_NAME : "codywaits-crc"

# Permission can be added at job level or workflow level    
permissions:
  id-token: write
  contents: read


jobs:
  deploy:
    name: Upload to Amazon S3
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::662458713737:role/GitHubAction-AssumeRoleWithAction
        aws-region: ${{ env.AWS_REGION }}
    - name: Copy files to the test website with the AWS CLI
      run: |
        aws s3 sync . s3://codywaits-crc